baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'my blog'

[markup]
  [markup.highlight]
  noClasses = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/project'
weight = 20 

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[taxonomies]
category = 'categories'
tag = "tags"

[pagination]
  disableAliases = false
  pagerSize = 2
  path = 'page'


[module]
  [module.hugoVersion]
    extended = true
    min = "0.116.0"
